// Generated by tools/i18n/compile.ts — do not edit.
export const AVAILABLE = [
	{
		"tag": "en"
	},
	{
		"tag": "qqx",
		"devOnly": true
	}
] as const;
export type AvailableLocale = (typeof AVAILABLE)[number]["tag"];
export const DEV = false;
