// Generated by tools/i18n/compile.ts from translation-languages.txt — do not edit.
// The selectable target languages, in the file's order (English first).
// Direction and display names are runtime concerns (core's isRTL and
// Intl.DisplayNames), so nothing but tag + English name is baked.
export const TRANSLATION_TARGETS = [
	{
		"tag": "en",
		"en": "English"
	},
	{
		"tag": "de",
		"en": "German"
	},
	{
		"tag": "fr",
		"en": "French"
	},
	{
		"tag": "es",
		"en": "Spanish"
	},
	{
		"tag": "it",
		"en": "Italian"
	},
	{
		"tag": "pt",
		"en": "Portuguese"
	},
	{
		"tag": "nl",
		"en": "Dutch"
	},
	{
		"tag": "sv",
		"en": "Swedish"
	},
	{
		"tag": "da",
		"en": "Danish"
	},
	{
		"tag": "nb",
		"en": "Norwegian Bokmål"
	},
	{
		"tag": "fi",
		"en": "Finnish"
	},
	{
		"tag": "pl",
		"en": "Polish"
	},
	{
		"tag": "cs",
		"en": "Czech"
	},
	{
		"tag": "sk",
		"en": "Slovak"
	},
	{
		"tag": "hu",
		"en": "Hungarian"
	},
	{
		"tag": "ro",
		"en": "Romanian"
	},
	{
		"tag": "bg",
		"en": "Bulgarian"
	},
	{
		"tag": "ru",
		"en": "Russian"
	},
	{
		"tag": "uk",
		"en": "Ukrainian"
	},
	{
		"tag": "sr",
		"en": "Serbian"
	},
	{
		"tag": "hr",
		"en": "Croatian"
	},
	{
		"tag": "sl",
		"en": "Slovenian"
	},
	{
		"tag": "el",
		"en": "Greek"
	},
	{
		"tag": "tr",
		"en": "Turkish"
	},
	{
		"tag": "ar",
		"en": "Arabic"
	},
	{
		"tag": "he",
		"en": "Hebrew"
	},
	{
		"tag": "fa",
		"en": "Persian"
	},
	{
		"tag": "hi",
		"en": "Hindi"
	},
	{
		"tag": "bn",
		"en": "Bangla"
	},
	{
		"tag": "ta",
		"en": "Tamil"
	},
	{
		"tag": "th",
		"en": "Thai"
	},
	{
		"tag": "vi",
		"en": "Vietnamese"
	},
	{
		"tag": "id",
		"en": "Indonesian"
	},
	{
		"tag": "ms",
		"en": "Malay"
	},
	{
		"tag": "zh",
		"en": "Chinese"
	},
	{
		"tag": "ja",
		"en": "Japanese"
	},
	{
		"tag": "ko",
		"en": "Korean"
	},
	{
		"tag": "ca",
		"en": "Catalan"
	},
	{
		"tag": "eu",
		"en": "Basque"
	},
	{
		"tag": "gl",
		"en": "Galician"
	},
	{
		"tag": "ga",
		"en": "Irish"
	},
	{
		"tag": "cy",
		"en": "Welsh"
	},
	{
		"tag": "sw",
		"en": "Swahili"
	},
	{
		"tag": "af",
		"en": "Afrikaans"
	},
	{
		"tag": "fil",
		"en": "Tagalog"
	},
	{
		"tag": "ur",
		"en": "Urdu"
	}
] as const;
export type TranslationTarget = (typeof TRANSLATION_TARGETS)[number];
