// Generated by tools/i18n/compile.ts from translation-languages.txt — do not edit.
// The selectable target languages, in the file's order (English first).
// Direction and display names are runtime concerns (core's isRTL and
// Intl.DisplayNames), so nothing but tag + English name is baked.
export const TRANSLATION_TARGETS = [
	{
		"tag": "en",
		"en": "English"
	},
	{
		"tag": "de",
		"en": "German"
	},
	{
		"tag": "fr",
		"en": "French"
	},
	{
		"tag": "es",
		"en": "Spanish"
	},
	{
		"tag": "it",
		"en": "Italian"
	},
	{
		"tag": "pt",
		"en": "Portuguese"
	},
	{
		"tag": "nl",
		"en": "Dutch"
	},
	{
		"tag": "sv",
		"en": "Swedish"
	},
	{
		"tag": "da",
		"en": "Danish"
	},
	{
		"tag": "pl",
		"en": "Polish"
	},
	{
		"tag": "cs",
		"en": "Czech"
	},
	{
		"tag": "sk",
		"en": "Slovak"
	},
	{
		"tag": "hu",
		"en": "Hungarian"
	},
	{
		"tag": "ro",
		"en": "Romanian"
	},
	{
		"tag": "ru",
		"en": "Russian"
	},
	{
		"tag": "uk",
		"en": "Ukrainian"
	},
	{
		"tag": "tr",
		"en": "Turkish"
	},
	{
		"tag": "ar",
		"en": "Arabic"
	},
	{
		"tag": "th",
		"en": "Thai"
	},
	{
		"tag": "vi",
		"en": "Vietnamese"
	},
	{
		"tag": "zh",
		"en": "Chinese"
	},
	{
		"tag": "ja",
		"en": "Japanese"
	},
	{
		"tag": "ko",
		"en": "Korean"
	},
	{
		"tag": "fil",
		"en": "Tagalog"
	}
] as const;
export type TranslationTarget = (typeof TRANSLATION_TARGETS)[number];
