// The locale tags a build ships in its pre-paint language resolution.
//
// `client/locales/tags.json` is generated by compile.ts and depends on no
// build mode (F13): it lists every compiled catalog, the dev-only rig
// included. Everything else filters the rig out at runtime through the
// bundler's own NODE_ENV fold (`client/js/i18n/core.ts` DEV_I18N), but the
// pre-paint script cannot — webpack substitutes the list into index.html as
// a literal — so the filter happens here, where webpack.config.ts reads the
// file and test/tests/i18n-toolchain.ts pins what it does.
//
// This module is listed in the root tsconfig.json's `files` because
// webpack.config.ts imports it (tools/ is otherwise outside that project).

import {readFileSync} from "node:fs";

/** Locales that exist for development only: the qqx pseudo-locale rig. */
export const DEV_ONLY_TAGS: readonly string[] = ["qqx"];

function isTagList(value: unknown): value is string[] {
	return Array.isArray(value) && value.every((tag) => typeof tag === "string");
}

/**
 * The tag list `path` holds, minus the dev-only locales for a production
 * build. Throws when the file is missing or is not a list of tags — a build
 * that silently shipped an empty list would resolve every visitor to en.
 */
export function readAvailableLocales(path: string, production: boolean): string[] {
	let raw: string;

	try {
		raw = readFileSync(path, "utf8");
	} catch (e: any) {
		throw new Error(
			`${path} is missing or unreadable — run "yarn i18n:compile" first: ${e.message}`
		);
	}

	const tags: unknown = JSON.parse(raw);

	if (!isTagList(tags)) {
		throw new Error(`${path} must be a JSON array of language tags`);
	}

	return production ? tags.filter((tag) => !DEV_ONLY_TAGS.includes(tag)) : tags;
}
