// The translation target list: translation-languages.txt (English names,
// one per line, curated by hand) mapped to BCP-47 tags and rendered into
// client/js/i18n/targets.ts. The selector lists every target; one whose
// catalog is not compiled yet renders disabled (English shows until its
// translation lands), so the list is the roadmap, not a lie.
//
// The txt carries English NAMES, not tags — the mapping lives here and is
// pinned to the file by test/tests/i18n-toolchain.ts. Adding a language to
// the txt without adding it here fails the compile with the name that has
// no tag; a tag that leaves the txt fails the live-tree test the same way.

import {readFileSync, writeFileSync} from "node:fs";
import {resolve} from "node:path";

/** translation-languages.txt, at the repository root. */
export const TARGETS_SOURCE = resolve("translation-languages.txt");

/** The generated module the client imports. */
export const TARGETS_PATH = resolve("client/js/i18n/targets.ts");

/** One selectable target language. */
export interface TranslationTarget {
	/** BCP-47 tag the catalogs and settings are keyed by. */
	tag: string;
	/** The English name from translation-languages.txt (the file's line). */
	en: string;
}

/** English name → tag. The names are translation-languages.txt's lines,
 * verbatim; a rename in the txt is a rename here. */
export const NAME_TO_TAG: Record<string, string> = {
	English: "en",
	German: "de",
	French: "fr",
	Spanish: "es",
	Italian: "it",
	Portuguese: "pt",
	Dutch: "nl",
	Swedish: "sv",
	Danish: "da",
	"Norwegian Bokmål": "nb",
	Finnish: "fi",
	Polish: "pl",
	Czech: "cs",
	Slovak: "sk",
	Hungarian: "hu",
	Romanian: "ro",
	Bulgarian: "bg",
	Russian: "ru",
	Ukrainian: "uk",
	Serbian: "sr",
	Croatian: "hr",
	Slovenian: "sl",
	Greek: "el",
	Turkish: "tr",
	Arabic: "ar",
	Hebrew: "he",
	Persian: "fa",
	Hindi: "hi",
	Bangla: "bn",
	Tamil: "ta",
	Thai: "th",
	Vietnamese: "vi",
	Indonesian: "id",
	Malay: "ms",
	Chinese: "zh",
	Japanese: "ja",
	Korean: "ko",
	Catalan: "ca",
	Basque: "eu",
	Galician: "gl",
	Irish: "ga",
	Welsh: "cy",
	Swahili: "sw",
	Afrikaans: "af",
	Tagalog: "fil",
	Urdu: "ur",
};

/** Parse the txt into targets, in file order. */
export function parseTargets(source: string): TranslationTarget[] {
	const names = source
		.split("\n")
		.map((line) => line.trim())
		.filter((line) => line.length > 0 && !line.startsWith("#"));

	const targets: TranslationTarget[] = [];

	for (const name of names) {
		const tag = NAME_TO_TAG[name];

		if (!tag) {
			throw new Error(
				`targets: "${name}" has no tag — add it to NAME_TO_TAG in tools/i18n/targets.ts`
			);
		}

		if (targets.some((target) => target.tag === tag)) {
			throw new Error(`targets: ${name} maps to ${tag}, which is already listed`);
		}

		targets.push({tag, en: name});
	}

	return targets;
}

/** Render the generated module: tags in file order, English first. */
export function renderTargets(targets: TranslationTarget[]): string {
	return (
		"// Generated by tools/i18n/compile.ts from translation-languages.txt — do not edit.\n" +
		"// The selectable target languages, in the file's order (English first).\n" +
		"// Direction and display names are runtime concerns (core's isRTL and\n" +
		"// Intl.DisplayNames), so nothing but tag + English name is baked.\n" +
		`export const TRANSLATION_TARGETS = ${JSON.stringify(targets, null, "\t")} as const;\n` +
		"export type TranslationTarget = (typeof TRANSLATION_TARGETS)[number];\n"
	);
}

/** Read the txt and write the generated module. */
export function generateTargets(
	sourcePath: string = TARGETS_SOURCE,
	outPath: string = TARGETS_PATH
): TranslationTarget[] {
	const targets = parseTargets(readFileSync(resolve(sourcePath), "utf8"));
	writeFileSync(resolve(outPath), renderTargets(targets));
	return targets;
}
